### ISSUE TITLE
Tech talk - Lika-liku Kerja Remote

### ISSUE THREAD

**Issue by herpiko** [LombokDev/Talks-Proposal#13]
Pembicara : Dzikri Aziz (@kucrut)

**Comment by ha-yi** [comment]
nah ini,,,, 💃

**Comment by sofyanhadia** [comment]
Could you please give us more description?
What "Lika-liku" are you gonna talk?

**Comment by herpiko** [comment]
@sofyanhadia General aspects of working remotely : pros, cons, communications, tips, improving productivity.

**Comment by herpiko** [comment]
Assigned to @kucrut
