### ISSUE TITLE
Tech Talk - Implementasi Google Maps API pada Android

### ISSUE THREAD

**Issue by ebysofyan** [LombokDev/Talks-Proposal#14]
Bagaimana sih cara implementasi Google Maps API di Android?
Apa saja sih yang dibutuhkan untuk bisa menampilkan maps di Android? 
Nantikan Tech Talknya di Lombok Dev Meetup mendatang . . .

**Comment by guntursulistyo** [comment]
2010 sy pernah buat apps pointer location pke api nya google map...kebayang android jaman itu?? wkwkw

**Comment by ebysofyan** [comment]
Wkwkwkwkkk android zaman bahula :D

**Comment by ha-yi** [comment]
@guntursulistyo listen location change aja sakit banget... -_- sampe puyeng ngoding nya...

**Comment by guntursulistyo** [comment]
tapi dulu apps sy bisa di pake buat tracking looh hahhaha..ada info lengkap sampe sak kecamatan hahahahah...

**Comment by ebysofyan** [comment]
Wahhh suhu suhu bernostalgia :D
