### ISSUE TITLE
Workshop - Android + TensorFlow: Bikin aplikasi android yg menyamai Seniman Kelas Dunia

### ISSUE THREAD

**Issue by ha-yi** [LombokDev/Talks-Proposal#15]
Nyobain bikin app yg dibuat di Google I/O 2017.

**Comment by sofyanhadia** [comment]
It's not about what you can make
but more like, let's bring this technology to help our community bla bla bla...
- How AI/ML/tensor flow will help our agriculture ...
- What model can we use ...
