### ISSUE TITLE
Tech Talk - Blockchain dan Hyperledger Fabric

### ISSUE THREAD

**Issue by herpiko** [LombokDev/Talks-Proposal#16]
Apa itu blockchain dan bagaimana membuat aplikasi berbasis blockchain? Hyperledger Fabric yang dirilis The Linux Foundation dapat membantu kita merancang aplikasi blockchain dengan konsensus yang efisien.

**Comment by guntursulistyo** [comment]
wiih berarti bisa buat cryptocurrency sendiri ini om..materi bagus ni...
