### ISSUE TITLE
Tech Talk - MVP an Introduction to Clean Code Architecture.

### ISSUE THREAD

**Issue by ha-yi** [LombokDev/Talks-Proposal#18]
Sebuah pengantar mengenai Konsep MPV dan Clean Code Architecture pada pengembangan Aplikasi Mobile dan Desktop. (Short Talk: +/-30 Min)

**Comment by khrlimam** [comment]
2017 issue, masih mau dibawakan bang? @ha-yi. Kalau tidak saya close ya.
