### ISSUE TITLE
Lightning Talk - Best Practice mencari Jodoh sebagai seorang Pemrogram

### ISSUE THREAD

**Issue by ebysofyan** [LombokDev/Talks-Proposal#19]
Sebagai seorang pemrogram tentu keseharian kita tidak jauh dengan yang namanya laptop dan perangkat pendukung lainnya. Terkadang hal tersebut sering membuat kita lupa untuk mengurus diri dan tidak memperhatikan kesehatan. Maka dari itu perlu _ada yang ngingetin, ada yang urusin, ada yang temenin_ . . .
**NGODING** ditemani **ISTRI** itu kan seru, **NGODINGNYA BAROKAHHH** . . . .

**Pemateri**: [Guntur Sulistyo Raharjo](https://github.com/guntursulistyo)

**Comment by guntursulistyo** [comment]
curhat?? wkwkwkwkwkwkwkwkwkwkkwkwk

**Comment by ebysofyan** [comment]
Nahhh cocok nih pak guntur yang bawain wkwkwkwkkk

**Comment by guntursulistyo** [comment]
haha maaf sy pria beristri yg standalone...wkwkwkkwkw

**Comment by ebysofyan** [comment]
Wkwkwkkkk >_<

**Comment by sofyanhadia** [comment]
Fuck man, don't do this... it's really shameful to play around like this
