### ISSUE TITLE
Fast MVP talks meterial

### ISSUE THREAD

**Issue by sofyanhadia** [LombokDev/Talks-Proposal#20]
Hi Guys, good job !!

But, IMO, it's better to give presentations about technologies that are happening right now and gives direct values
Why? It will help you guys to find job or freelance project or building our own startup
How about we talk about:
- ReactJS/Native + GraphQL
- Javascript/NodeJS to build MPV faster
- Cloud Infrastructure 
- Firebase/APIConnect/GraphCool
- Startup 101

**Comment by herpiko** [comment]
@sofyanhadia 

Hi, 

> about technologies that are happening right now

We are.

Please consult to https://github.com/LombokDev/Talks-Proposal/blob/master/README.md before creating any issue. You may join to the Telegram group ( lombokdev ) if you want to to discuss the topics with us.

Thank you.
