### ISSUE TITLE
Workshop - JWT dan Oauth

### ISSUE THREAD

**Issue by ardianta** [LombokDev/Talks-Proposal#21]
Implementasi JWT dan Oauth:

- introduction
- studi kasus
- best practice

Pemateri : Ardianta

~~P.S: cuma mau usul materi~~ :smile:

**Comment by herpiko** [comment]
@ardianta Yang ngusul yang garap. Mari saya sunting dikit.

**Comment by khyrulimam** [comment]
Kalo baca readme. Harusnya yang ngusul itu pemateri. Nah!

**Comment by ardianta** [comment]
![Noooooooooo](https://i.imgur.com/TsVS8h0.jpg)
