### ISSUE TITLE
Tech Talk - Game development - "Get Started & How To"

### ISSUE THREAD

**Issue by khyrulimam** [LombokDev/Talks-Proposal#3]
**Sekilas**: Suka dan ingin membuat game? Tidak tau mulai darimana? Tech Talk ini membahas tentang game dan bagaimana membangun game sendiri menggunakan C# & Unity

**Pembicara**: [M. Nasrul Alawy](https://github.com/alalawy)

**Comment by herpiko** [comment]
Terlaksana di meetup ke 3.
