### ISSUE TITLE
Tech Talk - Geographical Information System with React!

### ISSUE THREAD

**Issue by khyrulimam** [LombokDev/Talks-Proposal#4]
__Sekilas__: Dulu pernah belajar geografi di sekolah? Mau tau cara buat sistemnya? Pada Tech Talk ini kita akan membahas bagaimana membangun GIS dengan React.
__Pembicara__: [Subhan Nizar](https://www.linkedin.com/in/subhan-nizar-15a027131/)

**Comment by darmawan01** [comment]
gak bisa ambil fotonya pak

**Comment by herpiko** [comment]
Terlaksana di meetup ke 3.
