### ISSUE TITLE
Tech Talk - Ngoding Flutter Jadi Asik Dengan Atomic Designs

### ISSUE THREAD

**Issue by alalawy** [LombokDev/Talks-Proposal#47]
Pernah Gak Ngerasa Capek Saat Ngoding Flutter ? Gara2 Kodingan Numpuk di Satu Tempat dan Jadi Ribet Ketika Maintenance ? Nah Mari Kita Ubah Polanya Dengan Atomic Designs.

**Comment by khrlimam** [comment]
@alalawy please prepend the title with talk type e.g lightning talk or tech talk. I.e: Tech talk - Ngoding Flutter Jadi Asik Dengan Atomic Designs. Or lightning talk - Ngoding Flutter Jadi Asik Dengan Atomic Designs
