### ISSUE TITLE
Lightning Talk - Envoy proxy

### ISSUE THREAD

**Issue by darmawan01** [LombokDev/Talks-Proposal#49]
Envoy Proxy is a modern, high performance, small footprint edge and service proxy. Envoy is most comparable to software load balancers such as NGINX and HAProxy. Originally written and deployed at Lyft, Envoy now has a vibrant contributor base and is an official Cloud Native Computing Foundation project.

Introduce, why envoy, and other 🥳

**Comment by khrlimam** [comment]
Please specify the type. Tech talk or lightning talk?
