### ISSUE TITLE
Tech Talk - Taklukan SEO dengan Semantic Web

### ISSUE THREAD

**Issue by khyrulimam** [LombokDev/Talks-Proposal#5]
__Sekilas__: Membahas tentang teknologi Semantic Web yang digadang-gadang sebagai teknologi web cerdas masa depan, fungsinya dalam bidang AI dan SEO
__Pembicara__: [Syamsul Muttaqin](https://www.linkedin.com/in/syamsul-muttaqin-2b5828104/)

**Comment by Rhyxx404** [comment]
"SEO" Materi yang di tunggu-tunggu nih,

**Comment by herpiko** [comment]
Terlaksana di meetup ke 3.
