### ISSUE TITLE
Lightning talk - Semantic Search dengan ElasticSearch

### ISSUE THREAD

**Issue by ilham-bintang** [LombokDev/Talks-Proposal#56]
Ketika membuat apps, fitur searching sangat penting untuk mendukung pengalaman pengguna yang lebih baik.
Sebagai software engineer, query searching dengan `%LIKE%` adalah solusi yang paling mudah. Akan tetapi, bagaimana jika terdapat typo, atau dengan kata yang lebih mirip? Elastic search  bisa menjadi alternatif

- Pengenalan elasticsearch
- Kapan membutuhkan elasticsearch
- Arsitektur elasticsearch
- Elasticsearch index
- Searching (demo)

**Comment by anwar907** [comment]
> Ketika membuat apps, fitur searching sangat penting untuk mendukung pengalaman pengguna yang lebih baik.
> Sebagai software engineer, query searching dengan `%LIKE%` adalah solusi yang paling mudah. Akan tetapi, bagaimana jika terdapat typo, atau dengan kata yang lebih mirip? Elastic search bisa menjadi alternatif
> 
> * Pengenalan elasticsearch
> * Kapan membutuhkan elasticsearch
> * Arsitektur elasticsearch
> * Elasticsearch index
> * Searching (demo)

Sepertinya lebih ke Lightening Talks ni bang, sy update dulu ya:D
