### ISSUE TITLE
Tech Talk - Cara 'fun' membuat aplikasi android dengan Kotlin

### ISSUE THREAD

**Issue by ha-yi** [LombokDev/Talks-Proposal#6]
Gimana sih cara 'fun' ngoding aplikasi Android??

**Comment by khyrulimam** [comment]
Diperjelas pak _Tech Talk_ ato _Lighning Talk_
Format judul: **Konsep Talk** - **Judul**
refer ke [README.md](https://github.com/LombokDevMeetup/Talks-Proposal/blob/master/README.md)

**Comment by ha-yi** [comment]
done

**Comment by ha-yi** [comment]
ganti judu... XD

**Comment by sofyanhadia** [comment]
Like this one.
How about comparing Flutter+RactNative+Kotlin ?

**Comment by khyrulimam** [comment]
All talks material are open to propose. If You have any topic to talk about please submit proposal by following this instruction https://github.com/LombokDev/Talks-Proposal/blob/master/README.md (https://link.getmailspring.com/link/local-a3063306-c959-v1.1.4-22d9f20d@ThinkPad-T450/0?redirect=https%3A%2F%2Fgithub.com%2FLombokDev%2FTalks-Proposal%2Fblob%2Fmaster%2FREADME.md&recipient=reply%2B00a36027836b5671287fa20e7e75252906dadb32362064fb92cf0000000116a384ed92a169ce0fe739f5%40reply.github.com). And We will happyly arrange meetup to schedule your topic along with other materials. Thankyou
