### ISSUE TITLE
Workshop - Firebase in Action: Membuat Mobile App Tanpa Server dengan Firebase & Google App Engine.

### ISSUE THREAD

**Issue by ha-yi** [LombokDev/Talks-Proposal#8]
Membuat Aplikasi Mobile app yg client server nggak perlu server app, nggak perlu setup2 server dan database, cukup pake firebase dan google app engine.

**Comment by ha-yi** [comment]
umm,, btw sy masukin ide aja ya,, spa tau  ada temen2 yg mau jadi pematerinya.. :D

**Comment by sofyanhadia** [comment]
Not actually "Tanpa Server" 
But I like this ...

**Comment by khyrulimam** [comment]
That's actually literal translation from "serverless"
