### ISSUE TITLE
Tech Talk - WebVR: User happiness

### ISSUE THREAD

**Issue by khyrulimam** [LombokDev/Talks-Proposal#9]
**Sekilas**: Kupas Tuntas Web Virtual Reality, Konsep, Tech Stack, Libraries dan Implementasi UX
**Pembicara:** [Rizky Ariestiyansyah](https://www.linkedin.com/in/ariestiyansyah/)

**Comment by herpiko** [comment]
Terlaksana di meetup ke 3.
